export const styles = {
  root: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    background: "#0d0d14",
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    color: "#cdd6f4",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    borderBottom: "1px solid #1a1a2e",
    background: "#09090f",
    flexShrink: 0,
  },
  headerLeft: { display: "flex", alignItems: "center" },
  logo: {
    fontSize: 18,
    fontWeight: 700,
    color: "#39ff6e",
    letterSpacing: 2,
  },
  logoSub: {
    fontSize: 18,
    fontWeight: 400,
    color: "#585b70",
    letterSpacing: 2,
    marginRight: 16,
  },
  statusText: {
    fontSize: 11,
    color: "#585b70",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  stats: { display: "flex", alignItems: "center", gap: 8 },
  statLabel: { fontSize: 10, color: "#585b70", letterSpacing: 1 },
  statValue: {
    fontSize: 13,
    color: "#cdd6f4",
    fontVariantNumeric: "tabular-nums",
  },
  plotContainer: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "8px 12px",
  },
  channelWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  channelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "4px 8px",
    flexShrink: 0,
  },
  channelName: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 2,
  },
  channelSamples: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  channelPlot: {
    flex: 1,
    minHeight: 0,
  },
  plot: { width: "100%", height: "100%" },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 20px",
    borderTop: "1px solid #1a1a2e",
    background: "#09090f",
    flexShrink: 0,
  },
  btnBase: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 24px",
    border: "1px solid",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "inherit",
    letterSpacing: 2,
    transition: "opacity 0.15s",
  },
  btnStart: {
    background: "rgba(57, 255, 110, 0.08)",
    borderColor: "rgba(57, 255, 110, 0.3)",
    color: "#39ff6e",
  },
  btnStop: {
    background: "rgba(224, 108, 117, 0.08)",
    borderColor: "rgba(224, 108, 117, 0.3)",
    color: "#e06c75",
  },
  btnSettings: {
    background: "rgba(88, 91, 112, 0.08)",
    borderColor: "rgba(88, 91, 112, 0.3)",
    color: "#585b70",
    marginLeft: "auto",
    cursor: "pointer",
  },
  btnIcon: { fontSize: 10 },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0, 0, 0, 0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: "#12121c",
    border: "1px solid #1a1a2e",
    borderRadius: 10,
    width: 340,
    fontFamily: "'JetBrains Mono', monospace",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    borderBottom: "1px solid #1a1a2e",
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#cdd6f4",
    letterSpacing: 1,
  },
  modalClose: {
    background: "none",
    border: "none",
    color: "#585b70",
    fontSize: 16,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  modalBody: {
    padding: "18px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  fieldLabel: {
    fontSize: 11,
    color: "#585b70",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  toggleRow: {
    display: "flex",
    gap: 8,
  },
  toggleBtn: {
    flex: 1,
    padding: "8px 12px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#1a1a2e",
    borderRadius: 6,
    background: "#09090f",
    color: "#585b70",
    fontSize: 12,
    fontFamily: "inherit",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  toggleActive: {
    borderColor: "rgba(57, 255, 110, 0.4)",
    color: "#39ff6e",
    background: "rgba(57, 255, 110, 0.08)",
  },
  input: {
    padding: "8px 12px",
    border: "1px solid #1a1a2e",
    borderRadius: 6,
    background: "#09090f",
    color: "#cdd6f4",
    fontSize: 13,
    fontFamily: "inherit",
    outline: "none",
    width: "100%",
  },
};
